# -*- coding: utf-8 -*-
"""week2-A107260010-陳舒汶.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a_HSCkv526p9bwBoEgYTJBHEVspIapqQ
"""

print("Hello World")

import this